### ISSUE TITLE
F1 hybrid docs ?

### ISSUE THREAD

**Issue by colindaven** [churchill-lab/emase#4]
Hi,

thanks for a nice looking program. I'd be keen to try out the approach on F1 hybrids, but the documentation is not complete for this. Do you have any hints ?

So far I have created diploid pseudogenomes with my own program. I would like to realign RNA-seq reads this with STAR (complex plant genome, bowtie insufficient). 

Thanks,
Colin

**Comment by narayananr** [comment]
Hi
Thanks for the interest in using EMASE. Our current version of EMASE only supports aligning to transcriptome(s). Do you have annotations for the diploid genome? Then, the steps for F1 hybrids is exactly  the same as exmple given for human data. http://emase.readthedocs.org/en/latest/examples.html#estimating-allele-specific-expression-from-human-rna-seq-data

**Comment by colindaven** [comment]
Yes, we have annotations. 

I thought the method for F1 would be different, since this assumption is certainly not fulfilled, ie. we have no phased variant info, and certainly not for the whole population:

"
2. Build an individualized genome

We assume there is a vcf file that contains phased variant information for every sample of your population. Unless we know which allele is M(aternal) or P(aternal), we are going to distinguish two alleles with suffices, L(eft) and R(ight). We also recommend to use different ${SAMPLE_DIR} for each sample:
"

Thanks

**Comment by narayananr** [comment]
Sorry, I assumed that you have parental genomes (with their genetic variations). How did you create diploid pseudogenomes?

**Comment by colindaven** [comment]
My fault, I do.

I have trios, with rna-seq from the parents and the F1. I am pretty sure I don't have phased variant info  from the whole population (wouldn't this be a similar dataresource to the human Hapmap for example) ?

Anyway, I tried the prepare step, and had a nasty gtf error. Seems my GTFs do not have exon_number as your ensembl mouse GTFs do.
`
SBK4v2  SBKv2con_gmap   exon    9583833 9584107 100     -       .       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
SBK4v2  SBKv2con_gmap   exon    9582471 9582811 100     -       .       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
SBK4v2  SBKv2con_gmap   exon    9581356 9581460 100     -       .       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
SBK4v2  SBKv2con_gmap   exon    9581219 9581266 100     -       .       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
SBK4v2  SBKv2con_gmap   exon    9579406 9579910 100     -       .       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
SBK4v2  SBKv2con_gmap   CDS     9582471 9582743 100     -       0       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
SBK4v2  SBKv2con_gmap   CDS     9581356 9581460 100     -       0       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
SBK4v2  SBKv2con_gmap   CDS     9581219 9581266 100     -       0       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
SBK4v2  SBKv2con_gmap   CDS     9579671 9579910 100     -       0       gene_id "g2634.t1.path1"; transcript_id "g2634.t1.mrna1"; gene_name "g2634.t1";
####
`

**Comment by narayananr** [comment]
So, there is no parental genome sequence data available? Is one of the parents' reference genome available? In the case, it is not ideal, but one call variants using parental RNA-seq data and use it build diploid genome/transcriptome. I assume that is what you did for getting the diploid F1 genomes.  Can you share the GTF file, I will try to see what the problem is.

Thanks

**Comment by colindaven** [comment]
Thanks for your reply!

> > So, there is no parental genome sequence data available? Is one of the parents' reference genome available? 

Parental genomic resequencing data is available, but not of sufficient quality to build decent contigs or indeed a reference genome.

> > In the case, it is not ideal, but one call variants using parental RNA-seq data and use it build diploid genome/transcriptome. I assume that is what you did for getting the diploid F1 genomes. 

I exported parental SNPs in VCF from genomic requencing and used this to build the diploid genome only (dipl. transcriptome build failed). 

> > Can you share the GTF file, I will try to see what the problem is.

Apologies, I can't share it for this example. I have a second example with public data I might be able to share in the future - I may get back to you on this one but don't want to take up too much of your time.

**Comment by narayananr** [comment]
sure. no problem

**Comment by xdp7997** [comment]
Hello, I see that your team has been working on diploid transcriptome assembly. I am writing to inquire about how you achieved this successfully. I would also be very grateful if you could share any related publications for my reference.

> Thanks for your reply!感谢你的回复！
> 
> > > So, there is no parental genome sequence data available? Is one of the parents' reference genome available?所以，没有可用的亲本基因组序列数据？其中一个亲本的参考基因组可用吗？
> 
> Parental genomic resequencing data is available, but not of sufficient quality to build decent contigs or indeed a reference genome.亲本基因组重测序数据是可用的，但质量不足以构建良好的 contigs 或参考基因组。
> 
> > > In the case, it is not ideal, but one call variants using parental RNA-seq data and use it build diploid genome/transcriptome. I assume that is what you did for getting the diploid F1 genomes.在这种情况下，虽然不是理想的选择，但可以使用亲本 RNA-seq 数据来检测变异，并以此构建二倍体基因组/转录组。我猜这就是你用来获取二倍体 F1 基因组的方法。
> 
> I exported parental SNPs in VCF from genomic requencing and used this to build the diploid genome only (dipl. transcriptome build failed).我从基因组重测序数据中导出亲本 SNPs 到 VCF 文件，并仅使用这些数据来构建二倍体基因组（二倍体转录组构建失败）。
> 
> > > Can you share the GTF file, I will try to see what the problem is.你能分享一下 GTF 文件吗？我会尝试看看问题出在哪里。
> 
> Apologies, I can't share it for this example. I have a second example with public data I might be able to share in the future - I may get back to you on this one but don't want to take up too much of your time.抱歉，对于这个例子我无法分享。我有一个第二个例子，使用的是公开数据，我将来可能会分享。我可能会再回复你关于这个例子，但不想占用你太多时间。

Hello, I see that your team has been working on diploid transcriptome assembly. I am writing to inquire about how you achieved this successfully. I would also be very grateful if you could share any related publications for my reference.
