### ISSUE TITLE
emase.gene2transcripts.tsv is empty

### ISSUE THREAD

**Issue by lassancejm** [churchill-lab/emase#6]
Hi, 

I am willing to run Emase with F1 hybrid data and am running into an issue during the reference preparation. 

Basically, everything seems to be running fine (i.e. no error message produced), but the step "Recording mapping of gene id to transcript id's..." results into an empty emase.gene2transcripts.tsv file.  

Here is an example from the GTF, where gene1 encodes clearly several transcripts. 

NW_006501037.1  .   exon    6936    7096    0   -   .   gene_id "gene1"; transcript_id "mRNA1";
NW_006501037.1  .   CDS 6936    7096    0   -   2   gene_id "gene1"; transcript_id "mRNA1";
NW_006501037.1  .   exon    6936    7096    0   -   .   gene_id "gene1"; transcript_id "mRNA3";
NW_006501037.1  .   CDS 6936    7096    0   -   2   gene_id "gene1"; transcript_id "mRNA3";
NW_006501037.1  .   exon    6936    7096    0   -   .   gene_id "gene1"; transcript_id "mRNA4";
NW_006501037.1  .   CDS 6936    7096    0   -   2   gene_id "gene1"; transcript_id "mRNA4";
NW_006501037.1  .   exon    64350   64488   0   -   .   gene_id "gene1"; transcript_id "mRNA1";
NW_006501037.1  .   CDS 64350   64488   0   -   0   gene_id "gene1"; transcript_id "mRNA1";
NW_006501037.1  .   exon    64350   64488   0   -   .   gene_id "gene1"; transcript_id "mRNA3";
NW_006501037.1  .   CDS 64350   64488   0   -   0   gene_id "gene1"; transcript_id "mRNA3";

Do you have an idea of what may be going on here? Can I generate this file in any other way? 

Thanks 

JM

**Comment by kbchoi-jax** [comment]
I guess you got around it already. Could you share what the issue was?
