### ISSUE TITLE
dealing with paired-end reads

### ISSUE THREAD

**Issue by lassancejm** [churchill-lab/emase#7]
Hi, 

Going through the examples, I noticed that the alignment step is always done considering single-end data. Any particular reason for that?

If not, do you think it is ok to use the following parameters for the alignment:

`bowtie -a --best --strata -S -X 750 --chunkmbs 256 -p 16 ${bowtieidx} -1 ${prefix}.R1.fq -2 ${prefix}.R2.fq  | samtools view -F 0xC -bS - >${prefix}_emase.bam`

Thanks a lot!

**Comment by kbchoi-jax** [comment]
What I recommend for paired-end reads is to (1) run bowtie for each end independently, (2) convert each bam file to emase format, (3) combine two ends using the script, `get-common-alignments`, and then (4) run EM.

**Comment by lassancejm** [comment]
Will do as you recommend then, thank you.
