### ISSUE TITLE
ChIP-seq specific binding analysis

### ISSUE THREAD

**Issue by AlicePsyche** [churchill-lab/emase#8]
Hi, 

I want to use emase to do ChIP-seq allele specific binding analysis. The documentary says "While useing ChIP-seq, one needs to use **diploid binding target sequences** instead of **diploid transcriptome** for alignment target sequences." Does the _diploid binding target sequences_ refer to diploid genome file? I have generated two strains personalized genome files using g2gtools. How can I get something like S1xS2/emase.pooled.genome.fa? I am not sure if I understand the documentation correctly, could you please give me some more detail guides? 

Thanks in advance!

**Comment by kbchoi-jax** [comment]
I would rather suggest you excerpt binding sites from genomes. You can easily find corresponding regions between genomes using g2gtools (https://github.com/churchill-lab/g2gtools). Here is a nice example http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1004916. Using pooled genomes as a target is too much for efficient analysis.

**Comment by AlicePsyche** [comment]
Hi, 
Thanks for your quick reply.
After reading the paper, I still have some problems in practice. 
First, I extract genome ChIP-seq peaks region(called from MACS) using g2gtools, then I use `create-hybrid` to get emase.pooled.fa file, next I map fastq files to the pooled genome, last I should have been able to run `bam-to-emase` and `run-emase`, right ? But I failed getting emase format files from bam files, it kept saying header missing but I do have the header lines in bam file. 

``` bash
@HD     VN:1.0  SO:unsorted
@SQ     SN:chr3-2294_AB LN:200990
@SQ     SN:chr23-2546_AB        LN:110931
@SQ     SN:chr9-1657_AB LN:88048
@SQ     SN:chr19-1070_AB        LN:82044
@SQ     SN:chrM-14_AB   LN:16310
@SQ     SN:chr16-1490_AB        LN:46142
@SQ     SN:chr17-1721_AB        LN:44860
@SQ     SN:chr11-1225_AB        LN:44395
@SQ     SN:chr12-1867_AB        LN:36158
@SQ     SN:chr24-1918_AB        LN:35123
@SQ     SN:chr5-2915_AB LN:35230
@SQ     SN:chr18-1599_AB        LN:46533
@SQ     SN:chr9-928_AB  LN:34287
@SQ     SN:chr14-1437_AB        LN:28460
@SQ     SN:chr15-1943_AB        LN:39156
@SQ     SN:chr5-1520_AB LN:39206
```

Am I missing something necessary? Or I don't get the right emase workflow?

**Comment by kbchoi-jax** [comment]
Your workflow sounds solid. What strain IDs did you used for create-hybrid? _AB and what?

**Comment by AlicePsyche** [comment]
I solved the header thing, it seemed that the mapping was terminated by accident so I got a truncated bam file. But now I have another error:

```
File "/software/anaconda/envs/emase/bin/bam-to-emase", line 4, in <module>
    __import__('pkg_resources').run_script('emase==0.10.16', 'bam-to-emase')
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/software/anaconda/envs/emase/lib/python2.7/site-packages/emase-0.10.16-py2.7.egg-info/scripts/bam-to-emase", line 109, in <module>
    sys.exit(main())
  File "/software/anaconda/envs/emase/lib/python2.7/site-packages/emase-0.10.16-py2.7.egg-info/scripts/bam-to-emase", line 95, in main
    alignmat_factory.prepare(haplotypes, loci, outdir=os.path.dirname(outfile))
  File "/software/anaconda/envs/emase/lib/python2.7/site-packages/emase/AlignmentMatrixFactory.py", line 50, in prepare
    fhout[hap].write(struct.pack('>I', lid[locus]))
KeyError: 'chr7-4025'
```

I checked the *info file and couldn't see anything wrong:

```
chr7-4025_AB    4693
chr8-2646_AB    3651
chr8-2751_AB    4156
chr8-685_AB     2753
chr9-2399_AB    4399
```

The TU strain is also there:

```
chr17-1721_TU   44860
chr11-1225_TU   44395
chr12-1867_TU   36158
chr24-1918_TU   35123
chr5-2915_TU    35230
chr18-1599_TU   46533
```

Is it the right format?

**Comment by kbchoi-jax** [comment]
Usually you need to specify `-i emase.transcripts.info` that was created when you run `prepare-emase`. Since you are using your own targets, you should make a (column) list of common target names, i.e., without _AB or _TU.

```
    chr7-4025
    chr8-2646
    chr8-2751
    ...
    chr17-1721
    chr11-1225
    ...
```
